/* ============================================================
   Quiz Arena — questions.js
   Tüm sorular: Türkçe ve İngilizce
   8 kategori × 3 zorluk (easy / medium / hard)
   Her kategoride 10-15 soru/zorluk
   ============================================================ */

const QUESTIONS = {
  tr: {
    science: [
      {q:"Işığın boşluktaki hızı yaklaşık kaç km/s'dir?",o:["300.000","150.000","450.000","200.000"],a:0,d:"easy"},
      {q:"DNA'nın tam açılımı nedir?",o:["Deoksiribo Nükleik Asit","Dinitro Nükleik Asit","Difüzyon Nüklear Ajan","Deoksi Nitrat Asidi"],a:0,d:"easy"},
      {q:"Periyodik tabloda altının simgesi nedir?",o:["Au","Ag","Al","Ar"],a:0,d:"easy"},
      {q:"İnsan vücudunda kaç kemik bulunur?",o:["206","186","226","246"],a:0,d:"easy"},
      {q:"Su normal koşullarda kaç derecede kaynar?",o:["100°C","90°C","80°C","120°C"],a:0,d:"easy"},
      {q:"Güneş sistemimizdeki en büyük gezegen hangisidir?",o:["Jüpiter","Satürn","Uranüs","Neptün"],a:0,d:"easy"},
      {q:"İnsan vücudundaki en büyük organ hangisidir?",o:["Deri","Karaciğer","Akciğer","Kalp"],a:0,d:"easy"},
      {q:"Fotosentez sonucunda bitkilerin saldığı gaz nedir?",o:["Oksijen","Karbondioksit","Azot","Hidrojen"],a:0,d:"easy"},
      {q:"Atom çekirdeğinde bulunmayan parçacık hangisidir?",o:["Elektron","Proton","Nötron","Nükleon"],a:0,d:"medium"},
      {q:"Işığın su içindeki kırılma indisi yaklaşık kaçtır?",o:["1.33","1.00","2.42","1.50"],a:0,d:"medium"},
      {q:"Periyodik tabloda demir elementi hangi simgeyle gösterilir?",o:["Fe","Fr","Fo","Fi"],a:0,d:"medium"},
      {q:"İnsan kanının normal pH değeri kaçtır?",o:["7.4","6.5","8.0","5.5"],a:0,d:"medium"},
      {q:"Bir hücrenin enerji merkezi olarak bilinen organel hangisidir?",o:["Mitokondri","Ribozom","Kloroplast","Çekirdek"],a:0,d:"medium"},
      {q:"Ses hangi ortamda daha hızlı yayılır?",o:["Katı","Sıvı","Gaz","Boşluk"],a:0,d:"medium"},
      {q:"Suyun kimyasal formülü nedir?",o:["H₂O","H₂O₂","HO","H₃O"],a:0,d:"medium"},
      {q:"Schrödinger denklemi hangi bilim dalında kullanılır?",o:["Kuantum mekaniği","Termodinamik","Görelilik","Elektromanyetizma"],a:0,d:"hard"},
      {q:"Newton'un kaçıncı yasası F=ma ilişkisini tanımlar?",o:["İkinci","Birinci","Üçüncü","Dördüncü"],a:0,d:"hard"},
      {q:"Kelvin ölçeğinde mutlak sıfır kaç Kelvin'dir?",o:["0 K","-273 K","273 K","100 K"],a:0,d:"hard"},
      {q:"Bohr modelinde elektronlar nerede bulunur?",o:["Belirli enerji seviyelerinde","Çekirdekte","Rastgele konumlarda","Protonların arasında"],a:0,d:"hard"},
      {q:"Hangi element periyodik tabloda 'Hg' simgesiyle gösterilir?",o:["Cıva","Altın","Demir","Kurşun"],a:0,d:"hard"},
    ],
    history: [
      {q:"Osmanlı Devleti hangi yılda kuruldu?",o:["1299","1453","1071","1389"],a:0,d:"easy"},
      {q:"İstanbul'un fethini gerçekleştiren padişah kimdir?",o:["Fatih Sultan Mehmet","Yavuz Sultan Selim","Kanuni Sultan Süleyman","Murat II"],a:0,d:"easy"},
      {q:"Türkiye Cumhuriyeti hangi yılda ilan edildi?",o:["1923","1920","1919","1922"],a:0,d:"easy"},
      {q:"Birinci Dünya Savaşı hangi yılda başladı?",o:["1914","1918","1939","1905"],a:0,d:"easy"},
      {q:"Fransız Devrimi hangi yılda başladı?",o:["1789","1776","1815","1804"],a:0,d:"easy"},
      {q:"Atatürk hangi yılda vefat etmiştir?",o:["1938","1935","1940","1942"],a:0,d:"easy"},
      {q:"Amerika'nın bağımsızlık bildirisi hangi yılda ilan edildi?",o:["1776","1789","1800","1765"],a:0,d:"easy"},
      {q:"Kurtuluş Savaşı hangi antlaşmayla sona erdi?",o:["Lozan","Sevr","Mondros","Mudanya"],a:0,d:"medium"},
      {q:"Malazgirt Savaşı hangi yılda yaşandı?",o:["1071","1176","1243","1302"],a:0,d:"medium"},
      {q:"Osmanlı'da ilk matbaa kim tarafından kuruldu?",o:["İbrahim Müteferrika","Katip Çelebi","Evliya Çelebi","Piri Reis"],a:0,d:"medium"},
      {q:"Magna Carta ne zaman imzalandı?",o:["1215","1066","1492","1776"],a:0,d:"medium"},
      {q:"İkinci Dünya Savaşı hangi yılda sona erdi?",o:["1945","1944","1943","1946"],a:0,d:"medium"},
      {q:"Osmanlı'da Tanzimat Fermanı hangi yılda ilan edildi?",o:["1839","1856","1878","1908"],a:0,d:"medium"},
      {q:"Bizans İmparatorluğu'nun başkenti nereydi?",o:["Konstantinopolis","Roma","Atina","Antakya"],a:0,d:"hard"},
      {q:"Çanakkale Muharebesi hangi yıllarda yaşandı?",o:["1915-1916","1914-1915","1916-1917","1917-1918"],a:0,d:"hard"},
      {q:"Osmanlı'nın son padişahı kimdir?",o:["Mehmed VI","Abdülhamid II","Mehmed V","Abdülmecid II"],a:0,d:"hard"},
      {q:"Yavuz Sultan Selim Mısır'ı hangi savaşla fethetti?",o:["Ridaniye","Mercidabık","Çaldıran","Mohaç"],a:0,d:"hard"},
    ],
    culture: [
      {q:"Türkiye'nin başkenti neresidir?",o:["Ankara","İstanbul","İzmir","Bursa"],a:0,d:"easy"},
      {q:"Nobel Edebiyat Ödülü'nü kazanan ilk Türk yazar kimdir?",o:["Orhan Pamuk","Yaşar Kemal","Nazım Hikmet","Aziz Nesin"],a:0,d:"easy"},
      {q:"Mona Lisa tablosunun ressamı kimdir?",o:["Leonardo da Vinci","Michelangelo","Rafael","Botticelli"],a:0,d:"easy"},
      {q:"'1984' romanının yazarı kimdir?",o:["George Orwell","Aldous Huxley","Franz Kafka","Ernest Hemingway"],a:0,d:"easy"},
      {q:"Dünyada en çok konuşulan dil hangisidir?",o:["Mandarin Çincesi","İngilizce","İspanyolca","Hintçe"],a:0,d:"easy"},
      {q:"Romen rakamlarında 'X' hangi sayıyı temsil eder?",o:["10","5","15","20"],a:0,d:"easy"},
      {q:"Van Gogh'un 'Yıldızlı Gece' eseri hangi müzededir?",o:["MoMA","Louvre","Uffizi","Hermitage"],a:0,d:"medium"},
      {q:"Beethoven kaç senfoni besteledi?",o:["9","7","8","10"],a:0,d:"medium"},
      {q:"Shakespeare hangi ülkede doğdu?",o:["İngiltere","Fransa","Almanya","İtalya"],a:0,d:"medium"},
      {q:"Dünyanın en yüksek binası hangisidir?",o:["Burj Khalifa","Shanghai Tower","Abraj Al-Bait","Ping An Finance"],a:0,d:"medium"},
      {q:"'Suç ve Ceza' kitabının yazarı kimdir?",o:["Dostoyevski","Tolstoy","Çehov","Turgenev"],a:0,d:"medium"},
      {q:"Hangi müzik aleti 'keman ailesi'ne dahildir?",o:["Viyola","Tuba","Klarnet","Obua"],a:0,d:"medium"},
      {q:"Pablo Picasso hangi sanat akımının öncülerindendir?",o:["Kübizm","Empresyonizm","Sürrealizm","Dadaizm"],a:0,d:"hard"},
      {q:"Homeros'un İlyada destanının konusu nedir?",o:["Truva Savaşı","Odysseus'un yolculuğu","Herakles'in maceraları","Tanrıların savaşı"],a:0,d:"hard"},
      {q:"Dante'nin 'İlahi Komedya' eseri kaç bölümden oluşur?",o:["3","4","2","7"],a:0,d:"hard"},
    ],
    sports: [
      {q:"FIFA Dünya Kupası kaç yılda bir düzenlenir?",o:["4","2","3","5"],a:0,d:"easy"},
      {q:"Basketbolda bir maç kaç periyottan oluşur?",o:["4","2","3","5"],a:0,d:"easy"},
      {q:"Olimpiyat bayrağında kaç halka vardır?",o:["5","4","6","7"],a:0,d:"easy"},
      {q:"Tenis'te grand slam kaç turnuvadan oluşur?",o:["4","2","3","5"],a:0,d:"easy"},
      {q:"Futbolda normal bir maç kaç dakikadır?",o:["90","80","100","120"],a:0,d:"easy"},
      {q:"Hangi ülke en fazla FIFA Dünya Kupası kazanmıştır?",o:["Brezilya","Almanya","İtalya","Arjantin"],a:0,d:"easy"},
      {q:"NBA'de bir maç kaç dakikadır?",o:["48","40","60","36"],a:0,d:"medium"},
      {q:"Voleybolda bir seti kazanmak için kaç sayı gerekir?",o:["25","21","15","30"],a:0,d:"medium"},
      {q:"Türkiye'nin en fazla Süper Lig şampiyonluğu olan takımı?",o:["Galatasaray","Fenerbahçe","Beşiktaş","Trabzonspor"],a:0,d:"medium"},
      {q:"Formula 1'de en fazla şampiyonluk kazanan pilot kimdir?",o:["Lewis Hamilton","Michael Schumacher","Ayrton Senna","Sebastian Vettel"],a:0,d:"medium"},
      {q:"Yüzmede 'kelebek' stilinde kollar nasıl kullanılır?",o:["Her iki kol aynı anda","Sırayla kollar","Sadece bacaklar","Sadece kollar"],a:0,d:"medium"},
      {q:"Usain Bolt'un 100m dünya rekoru kaç saniyedir?",o:["9.58","9.63","9.69","9.72"],a:0,d:"hard"},
      {q:"Rugby union takımında kaç oyuncu bulunur?",o:["15","11","13","7"],a:0,d:"hard"},
      {q:"En yüksek rakımlı futbol sahası hangi ülkededir?",o:["Bolivya","Peru","Ekvador","Kolombiya"],a:0,d:"hard"},
    ],
    geo: [
      {q:"Dünyanın en büyük kıtası hangisidir?",o:["Asya","Afrika","Amerika","Avrupa"],a:0,d:"easy"},
      {q:"Türkiye hangi iki kıta üzerinde yer alır?",o:["Asya ve Avrupa","Asya ve Afrika","Avrupa ve Afrika","Asya ve Avustralya"],a:0,d:"easy"},
      {q:"Dünyanın en uzun nehri hangisidir?",o:["Nil","Amazon","Yangtze","Mississippi"],a:0,d:"easy"},
      {q:"Everest Dağı hangi ülkede yer alır?",o:["Nepal","Çin","Hindistan","Tibet"],a:0,d:"easy"},
      {q:"Hangi şehir hem Asya hem Avrupa'da yer alır?",o:["İstanbul","Moskova","Kahire","Tahran"],a:0,d:"easy"},
      {q:"Dünya'nın en büyük okyanusu hangisidir?",o:["Pasifik","Atlantik","Hint","Arktik"],a:0,d:"easy"},
      {q:"En fazla ülkeyle sınırı olan ülke hangisidir?",o:["Çin","Rusya","Brezilya","Almanya"],a:0,d:"medium"},
      {q:"Akdeniz'e kıyısı olmayan ülke hangisidir?",o:["Portekiz","İspanya","İtalya","Fransa"],a:0,d:"medium"},
      {q:"Amazon Nehri hangi okyanusa dökülür?",o:["Atlantik","Pasifik","Hint","Karayip"],a:0,d:"medium"},
      {q:"Türkiye'nin yüzölçümü yaklaşık kaç km²'dir?",o:["783.000","500.000","900.000","650.000"],a:0,d:"medium"},
      {q:"Dünyanın en büyük çölü hangisidir?",o:["Antarktika","Sahara","Gobi","Arabistan"],a:0,d:"hard"},
      {q:"Türkiye'nin en uzun nehri hangisidir?",o:["Kızılırmak","Fırat","Sakarya","Yeşilırmak"],a:0,d:"hard"},
      {q:"Dünyanın en küçük ülkesi hangisidir?",o:["Vatikan","Monako","San Marino","Liechtenstein"],a:0,d:"hard"},
      {q:"Himalayalar hangi iki levhanın çarpışmasıyla oluşmuştur?",o:["Hint-Avrasya","Pasifik-Avrasya","Hint-Afrika","Afrika-Avrasya"],a:0,d:"hard"},
    ],
    tech: [
      {q:"WWW'nin mucidi kimdir?",o:["Tim Berners-Lee","Bill Gates","Steve Jobs","Linus Torvalds"],a:0,d:"easy"},
      {q:"HTML ne anlama gelir?",o:["HyperText Markup Language","High Transfer Markup Language","HyperText Management Language","High Text Markup Language"],a:0,d:"easy"},
      {q:"İlk iPhone hangi yılda tanıtıldı?",o:["2007","2005","2009","2010"],a:0,d:"easy"},
      {q:"CSS web geliştirmede ne işe yarar?",o:["Stil ve tasarım","Veri tabanı yönetimi","Sunucu kodlama","Ağ iletişimi"],a:0,d:"easy"},
      {q:"Bir kilobayt (KB) kaç bayttır?",o:["1024","1000","512","2048"],a:0,d:"easy"},
      {q:"Google hangi yılda kuruldu?",o:["1998","1995","2000","2004"],a:0,d:"easy"},
      {q:"JavaScript'te 'null' ve 'undefined' farkı nedir?",o:["Null kasıtlı, undefined bildirilmemiş","İkisi aynıdır","Undefined kasıtlı","İkisi de hata türüdür"],a:0,d:"medium"},
      {q:"HTTP yanıt kodu 404 ne anlama gelir?",o:["Bulunamadı","Sunucu Hatası","Yetkisiz","Başarılı"],a:0,d:"medium"},
      {q:"Linux çekirdeği kim tarafından geliştirildi?",o:["Linus Torvalds","Richard Stallman","Dennis Ritchie","Ken Thompson"],a:0,d:"medium"},
      {q:"Hangi protokol güvenli web trafiği için kullanılır?",o:["HTTPS","HTTP","FTP","SMTP"],a:0,d:"medium"},
      {q:"SQL'de veri çekmek için hangi komut kullanılır?",o:["SELECT","GET","FETCH","READ"],a:0,d:"medium"},
      {q:"Python hangi tür programlama dilidir?",o:["Yorumlanan","Derlenen","Assembly","Makine dili"],a:0,d:"medium"},
      {q:"Git'te 'merge' ve 'rebase' arasındaki temel fark nedir?",o:["Merge dalları birleştirir, rebase tabanı değiştirir","İkisi aynıdır","Rebase siler","Merge geri alır"],a:0,d:"hard"},
      {q:"Big O notasyonunda O(log n) hangi algoritmayı tanımlar?",o:["İkili arama","Kabarcık sıralaması","Doğrusal arama","Ekleme sıralaması"],a:0,d:"hard"},
      {q:"TCP/IP modelinde kaç katman bulunur?",o:["4","7","3","5"],a:0,d:"hard"},
      {q:"Bir IPv4 adresi kaç bitten oluşur?",o:["32","64","128","16"],a:0,d:"hard"},
    ],
    math: [
      {q:"π (pi) sayısının yaklaşık değeri nedir?",o:["3.14","3.41","3.12","3.18"],a:0,d:"easy"},
      {q:"2⁸ kaçtır?",o:["256","128","512","64"],a:0,d:"easy"},
      {q:"Bir üçgenin iç açıları toplamı kaç derecedir?",o:["180","360","90","270"],a:0,d:"easy"},
      {q:"√144 kaçtır?",o:["12","11","13","14"],a:0,d:"easy"},
      {q:"0.5'in yüzde karşılığı nedir?",o:["%50","%5","%0.5","%500"],a:0,d:"easy"},
      {q:"Bir küpün kaç yüzeyi vardır?",o:["6","4","8","12"],a:0,d:"easy"},
      {q:"Bir dairenin çevresi hangi formülle hesaplanır?",o:["2πr","πr²","4πr","πd²"],a:0,d:"medium"},
      {q:"Fibonacci dizisinde 8'den sonra gelen sayı nedir?",o:["13","11","16","21"],a:0,d:"medium"},
      {q:"log₁₀(1000) kaçtır?",o:["3","4","2","10"],a:0,d:"medium"},
      {q:"(-3)² kaçtır?",o:["9","-9","6","-6"],a:0,d:"medium"},
      {q:"Bir dikdörtgenin alanı nasıl hesaplanır?",o:["En × Boy","2×(En+Boy)","En+Boy","En²"],a:0,d:"medium"},
      {q:"e (Euler sayısı) yaklaşık olarak kaçtır?",o:["2.718","2.414","3.141","1.618"],a:0,d:"hard"},
      {q:"Sin(90°) kaçtır?",o:["1","0","-1","√2/2"],a:0,d:"hard"},
      {q:"Bir kürenin hacmi hangi formülle hesaplanır?",o:["(4/3)πr³","4πr²","πr³","(2/3)πr³"],a:0,d:"hard"},
      {q:"Asal sayıların sonsuz olduğunu ilk ispatlayan matematikçi kimdir?",o:["Öklid","Pisagor","Arşimet","Fermat"],a:0,d:"hard"},
    ],
  },
  en: {
    science: [
      {q:"Speed of light in km/s?",o:["300,000","150,000","450,000","200,000"],a:0,d:"easy"},
      {q:"What does DNA stand for?",o:["Deoxyribonucleic Acid","Dinitrogen Nucleic Acid","Diffusion Nuclear Agent","Deoxy Nitrate Acid"],a:0,d:"easy"},
      {q:"Chemical symbol for gold?",o:["Au","Ag","Al","Ar"],a:0,d:"easy"},
      {q:"Bones in the adult human body?",o:["206","186","226","246"],a:0,d:"easy"},
      {q:"Boiling point of water at sea level?",o:["100°C","90°C","80°C","120°C"],a:0,d:"easy"},
      {q:"Largest planet in the solar system?",o:["Jupiter","Saturn","Uranus","Neptune"],a:0,d:"easy"},
      {q:"Largest organ in the human body?",o:["Skin","Liver","Lung","Heart"],a:0,d:"easy"},
      {q:"Gas released by plants during photosynthesis?",o:["Oxygen","Carbon dioxide","Nitrogen","Hydrogen"],a:0,d:"easy"},
      {q:"Particle NOT found in the atomic nucleus?",o:["Electron","Proton","Neutron","Nucleon"],a:0,d:"medium"},
      {q:"Refractive index of water for light?",o:["1.33","1.00","2.42","1.50"],a:0,d:"medium"},
      {q:"Chemical symbol for iron?",o:["Fe","Fr","Fo","In"],a:0,d:"medium"},
      {q:"Normal human blood pH?",o:["7.4","6.5","8.0","5.5"],a:0,d:"medium"},
      {q:"Organelle known as the powerhouse of the cell?",o:["Mitochondria","Ribosome","Chloroplast","Nucleus"],a:0,d:"medium"},
      {q:"In which medium does sound travel fastest?",o:["Solid","Liquid","Gas","Vacuum"],a:0,d:"medium"},
      {q:"Chemical formula of water?",o:["H₂O","H₂O₂","HO","H₃O"],a:0,d:"medium"},
      {q:"Schrödinger equation is used in?",o:["Quantum mechanics","Thermodynamics","Relativity","Electromagnetism"],a:0,d:"hard"},
      {q:"Newton's law that defines F=ma?",o:["Second","First","Third","Fourth"],a:0,d:"hard"},
      {q:"Absolute zero in Kelvin?",o:["0 K","-273 K","273 K","100 K"],a:0,d:"hard"},
      {q:"Where are electrons in the Bohr model?",o:["Specific energy levels","In the nucleus","Random positions","Between protons"],a:0,d:"hard"},
      {q:"Element with symbol 'Hg'?",o:["Mercury","Gold","Iron","Lead"],a:0,d:"hard"},
    ],
    history: [
      {q:"Ottoman Empire founded in?",o:["1299","1453","1071","1389"],a:0,d:"easy"},
      {q:"Who conquered Constantinople in 1453?",o:["Mehmed II","Suleiman the Magnificent","Selim I","Murad II"],a:0,d:"easy"},
      {q:"WWI began in?",o:["1914","1918","1939","1905"],a:0,d:"easy"},
      {q:"French Revolution began in?",o:["1789","1776","1815","1804"],a:0,d:"easy"},
      {q:"First person to walk on the Moon?",o:["Neil Armstrong","Buzz Aldrin","Yuri Gagarin","John Glenn"],a:0,d:"easy"},
      {q:"US Declaration of Independence signed in?",o:["1776","1789","1800","1765"],a:0,d:"easy"},
      {q:"WWII ended in?",o:["1945","1944","1943","1946"],a:0,d:"easy"},
      {q:"Treaty that ended WWI?",o:["Treaty of Versailles","Treaty of Sèvres","Brest-Litovsk","Treaty of Lausanne"],a:0,d:"medium"},
      {q:"Magna Carta signed in?",o:["1215","1066","1492","1776"],a:0,d:"medium"},
      {q:"Capital of the Byzantine Empire?",o:["Constantinople","Rome","Athens","Antioch"],a:0,d:"medium"},
      {q:"Battle of Waterloo took place in?",o:["1815","1804","1812","1821"],a:0,d:"medium"},
      {q:"Ottoman Tanzimat reforms began in?",o:["1839","1856","1878","1908"],a:0,d:"medium"},
      {q:"Last Ottoman Sultan?",o:["Mehmed VI","Abdülhamid II","Mehmed V","Abdülmecid II"],a:0,d:"hard"},
      {q:"Battle that opened Anatolia to Seljuks?",o:["Manzikert","Hattin","Myriokephalon","Köse Dağ"],a:0,d:"hard"},
      {q:"Treaty that ended the Turkish War of Independence?",o:["Lausanne","Sèvres","Mondros","Mudanya"],a:0,d:"hard"},
    ],
    culture: [
      {q:"Capital of Turkey?",o:["Ankara","Istanbul","Izmir","Bursa"],a:0,d:"easy"},
      {q:"Who painted the Mona Lisa?",o:["Leonardo da Vinci","Michelangelo","Raphael","Botticelli"],a:0,d:"easy"},
      {q:"Who wrote '1984'?",o:["George Orwell","Aldous Huxley","Franz Kafka","Ernest Hemingway"],a:0,d:"easy"},
      {q:"Most spoken language in the world?",o:["Mandarin Chinese","English","Spanish","Hindi"],a:0,d:"easy"},
      {q:"X in Roman numerals?",o:["10","5","15","20"],a:0,d:"easy"},
      {q:"Where is Van Gogh's 'The Starry Night'?",o:["MoMA","Louvre","Uffizi","Hermitage"],a:0,d:"medium"},
      {q:"Symphonies composed by Beethoven?",o:["9","7","8","10"],a:0,d:"medium"},
      {q:"Shakespeare's birth country?",o:["England","France","Germany","Italy"],a:0,d:"medium"},
      {q:"World's tallest building?",o:["Burj Khalifa","Shanghai Tower","Abraj Al-Bait","Ping An Finance"],a:0,d:"medium"},
      {q:"Who wrote 'Crime and Punishment'?",o:["Dostoevsky","Tolstoy","Chekhov","Turgenev"],a:0,d:"medium"},
      {q:"Picasso pioneered which art movement?",o:["Cubism","Impressionism","Surrealism","Dadaism"],a:0,d:"hard"},
      {q:"Homer's Iliad is about which war?",o:["Trojan War","Odysseus' journey","Heracles' labors","War of the gods"],a:0,d:"hard"},
      {q:"Dante's 'Divine Comedy' has how many parts?",o:["3","4","2","7"],a:0,d:"hard"},
    ],
    sports: [
      {q:"FIFA World Cup held every?",o:["4 years","2 years","3 years","5 years"],a:0,d:"easy"},
      {q:"Quarters in a basketball game?",o:["4","2","3","5"],a:0,d:"easy"},
      {q:"Rings on the Olympic flag?",o:["5","4","6","7"],a:0,d:"easy"},
      {q:"Grand Slam tournaments in tennis?",o:["4","2","3","5"],a:0,d:"easy"},
      {q:"Standard football match duration?",o:["90 min","80 min","100 min","120 min"],a:0,d:"easy"},
      {q:"Country with most World Cup titles?",o:["Brazil","Germany","Italy","Argentina"],a:0,d:"easy"},
      {q:"NBA game duration?",o:["48 min","40 min","60 min","36 min"],a:0,d:"medium"},
      {q:"Points to win a volleyball set?",o:["25","21","15","30"],a:0,d:"medium"},
      {q:"Most F1 championship titles?",o:["Lewis Hamilton","Michael Schumacher","Ayrton Senna","Sebastian Vettel"],a:0,d:"medium"},
      {q:"Butterfly stroke arm movement?",o:["Both arms simultaneously","Alternating arms","Only legs","Only arms"],a:0,d:"medium"},
      {q:"Usain Bolt's 100m world record?",o:["9.58s","9.63s","9.69s","9.72s"],a:0,d:"hard"},
      {q:"Players in a rugby union team?",o:["15","11","13","7"],a:0,d:"hard"},
      {q:"Country with highest altitude football stadium?",o:["Bolivia","Peru","Ecuador","Colombia"],a:0,d:"hard"},
    ],
    geo: [
      {q:"Largest continent?",o:["Asia","Africa","America","Europe"],a:0,d:"easy"},
      {q:"Longest river in the world?",o:["Nile","Amazon","Yangtze","Mississippi"],a:0,d:"easy"},
      {q:"Tallest mountain in the world?",o:["Everest","K2","Kangchenjunga","Lhotse"],a:0,d:"easy"},
      {q:"City on both Asia and Europe?",o:["Istanbul","Moscow","Cairo","Tehran"],a:0,d:"easy"},
      {q:"World's largest ocean?",o:["Pacific","Atlantic","Indian","Arctic"],a:0,d:"easy"},
      {q:"Country bordering the most nations?",o:["China","Russia","Brazil","Germany"],a:0,d:"medium"},
      {q:"Country NOT on the Mediterranean?",o:["Portugal","Spain","Italy","France"],a:0,d:"medium"},
      {q:"Amazon River flows into?",o:["Atlantic","Pacific","Indian","Caribbean"],a:0,d:"medium"},
      {q:"Most populous country in 2024?",o:["India","China","USA","Indonesia"],a:0,d:"medium"},
      {q:"World's largest desert?",o:["Antarctica","Sahara","Gobi","Arabian"],a:0,d:"hard"},
      {q:"World's smallest country?",o:["Vatican","Monaco","San Marino","Liechtenstein"],a:0,d:"hard"},
      {q:"Himalayas formed by collision of?",o:["Indian-Eurasian plates","Pacific-Eurasian","Indian-African","African-Eurasian"],a:0,d:"hard"},
    ],
    tech: [
      {q:"Who invented the World Wide Web?",o:["Tim Berners-Lee","Bill Gates","Steve Jobs","Linus Torvalds"],a:0,d:"easy"},
      {q:"HTML stands for?",o:["HyperText Markup Language","High Transfer Markup Language","HyperText Management Language","High Text Markup Language"],a:0,d:"easy"},
      {q:"First iPhone unveiled in?",o:["2007","2005","2009","2010"],a:0,d:"easy"},
      {q:"CSS stands for?",o:["Cascading Style Sheets","Computer Style Sheets","Creative Style System","Coded Style Sheets"],a:0,d:"easy"},
      {q:"Bytes in a kilobyte?",o:["1024","1000","512","2048"],a:0,d:"easy"},
      {q:"Google founded in?",o:["1998","1995","2000","2004"],a:0,d:"easy"},
      {q:"HTTP status 404 means?",o:["Not Found","Server Error","Unauthorized","Success"],a:0,d:"medium"},
      {q:"Who created the Linux kernel?",o:["Linus Torvalds","Richard Stallman","Dennis Ritchie","Ken Thompson"],a:0,d:"medium"},
      {q:"Protocol for secure web traffic?",o:["HTTPS","HTTP","FTP","SMTP"],a:0,d:"medium"},
      {q:"SQL command to retrieve data?",o:["SELECT","GET","FETCH","READ"],a:0,d:"medium"},
      {q:"null vs undefined in JavaScript?",o:["Null is intentional, undefined is undeclared","They are identical","Undefined is intentional","Both are errors"],a:0,d:"medium"},
      {q:"Python is what type of language?",o:["Interpreted","Compiled","Assembly","Machine language"],a:0,d:"medium"},
      {q:"O(log n) describes which algorithm?",o:["Binary search","Bubble sort","Linear search","Insertion sort"],a:0,d:"hard"},
      {q:"Layers in the TCP/IP model?",o:["4","7","3","5"],a:0,d:"hard"},
      {q:"IPv4 address bit count?",o:["32","64","128","16"],a:0,d:"hard"},
      {q:"git merge vs rebase key difference?",o:["Merge joins histories, rebase moves base","They are the same","Rebase deletes commits","Merge reverts changes"],a:0,d:"hard"},
    ],
    math: [
      {q:"Approximate value of π?",o:["3.14","3.41","3.12","3.18"],a:0,d:"easy"},
      {q:"2⁸ equals?",o:["256","128","512","64"],a:0,d:"easy"},
      {q:"Sum of interior angles of a triangle?",o:["180°","360°","90°","270°"],a:0,d:"easy"},
      {q:"√144 equals?",o:["12","11","13","14"],a:0,d:"easy"},
      {q:"0.5 as a percentage?",o:["50%","5%","0.5%","500%"],a:0,d:"easy"},
      {q:"Faces on a cube?",o:["6","4","8","12"],a:0,d:"easy"},
      {q:"Circumference of a circle formula?",o:["2πr","πr²","4πr","πd²"],a:0,d:"medium"},
      {q:"Fibonacci number after 8?",o:["13","11","16","21"],a:0,d:"medium"},
      {q:"log₁₀(1000) equals?",o:["3","4","2","10"],a:0,d:"medium"},
      {q:"(-3)² equals?",o:["9","-9","6","-6"],a:0,d:"medium"},
      {q:"Area of a rectangle formula?",o:["Length × Width","2×(L+W)","L+W","L²"],a:0,d:"medium"},
      {q:"Euler's number (e) approximately?",o:["2.718","2.414","3.141","1.618"],a:0,d:"hard"},
      {q:"Sin(90°) equals?",o:["1","0","-1","√2/2"],a:0,d:"hard"},
      {q:"Volume of a sphere formula?",o:["(4/3)πr³","4πr²","πr³","(2/3)πr³"],a:0,d:"hard"},
      {q:"Who first proved infinite primes?",o:["Euclid","Pythagoras","Archimedes","Fermat"],a:0,d:"hard"},
    ],
  },
};
